git add Address.cs
git add App.config
git add Category.cs
git add CodeFragments.txt
git add Commit.bat
git add computerdepot
git add computerdepot.csproj
git add computerdepot.csproj.user
git add ComputerDepot.mdf
git add computerdepot.sln
git add ComputerDepotMainForm.cs
git add ComputerDepotMainForm.Designer.cs
git add ComputerDepotMainForm.resx
git add ComputerDepot_log.ldf
git add Customer.cs
git add CustomerForm.cs
git add CustomerForm.Designer.cs
git add CustomerForm.resx
git add Customers.cs
git add Database.cs
git add Discount.cs
git add Discounts.cs
git add Email.cs
git add Employee Identification Number.cs
git add Employee Identification Number.Designer.cs
git add Employee Identification Number.resx
git add Employee.cs
git add EmployeeInformation.cs
git add EmployeeInformation.Designer.cs
git add EmployeeInformation.resx
git add ErrorChecker.cs
git add ErrorCodes.cs
git add Form1.cs
git add Form1.Designer.cs
git add Form1.resx
git add Inventories.cs
git add Inventory.cs
git add INVENTORYForm.cs
git add INVENTORYForm.Designer.cs
git add INVENTORYForm.resx
git add InventoryReport.cs
git add Login.cs
git add Login.Designer.cs
git add Login.resx
git add Message1.cs
git add Message1.Designer.cs
git add Message1.resx
git add ModelingProject1
git add ModelingProject2
git add Order.cs
git add OrderDetails.cs
git add OrderDetails.Designer.cs
git add OrderDetails.resx
git add OrderHistory.cs
git add OrderHistory.Designer.cs
git add OrderHistory.resx
git add OrderItem.cs
git add OrderNew.cs
git add OrderNew.Designer.cs
git add OrderNew.resx
git add OrderReport.docx
git add Orders.cs
git add OrdersReport.cs
git add Phone.cs
git add Product.cs
git add Products.cs
git add Program.cs
git add Properties
git add Report.cs
git add ReportingForm.cs
git add ReportingForm.Designer.cs
git add ReportingForm.resx
git add Reports.cs
git add Service.cs
git add Services.cs
git add Settings.cs
git add Ship.cs
git add Ship.Designer.cs
git add Ship.resx
git add "Shipping Request.cs"
git add "Shipping Request.Designer.cs"
git add "Shipping Request.resx"
git add SupplierDetails.cs
git add SupplierDetails.Designer.cs
git add SupplierDetails.resx
git add WordReport.cs
